<?php
# this file is auto-generated by bundler 2015-09-24 22:10:48
return array (
  'javascriptFoo' => 
  array (
    'md5' => '33e7f1549ea0723bef1b6b00b598f088',
    'max' => 'js/javascriptFoo.max.js',
    'min' => 'js/javascriptFoo.min.js',
  ),
  'javascriptBar' => 
  array (
    'md5' => '81db9d412081086a63735cfd8378385c',
    'max' => 'js/javascriptBar.max.js',
    'min' => 'js/javascriptBar.min.js',
  ),
);