<?php
# this file is auto-generated by bundler
return array(
    'javascriptFoo' => array(
        'md5' => 'cf1c4502fb665807b78f2f1ea6619f81',
        'max' => 'js/javascriptFoo.max.js',
        'min' => 'js/javascriptFoo.min.js',
    ),
    'javascriptBar' => array(
        'md5' => '82c15fd14a6a11f4535b57221e79c9c6',
        'max' => 'js/javascriptBar.max.js',
        'min' => 'js/javascriptBar.min.js',
    ),
);