<?php
# this file is auto-generated by bundler 2015-11-23 23:20:02
return array (
  'stylesheetFoo' => 
  array (
    'md5' => 'e62ee3289506144e4a2c7158202db4da',
    'max' => 'css/stylesheetFoo.max.css',
    'min' => 'css/stylesheetFoo.min.css',
  ),
  'stylesheetBar' => 
  array (
    'md5' => 'a21d8c42c6d63bbadc0c9aa9d371aaf2',
    'max' => 'css/stylesheetBar.max.css',
    'min' => 'css/stylesheetBar.min.css',
  ),
);