<?php
# this file is auto-generated by bundler
return array(
    'stylesheetFoo' => array(
        'md5' => '0aed497cc25bfc6ad59025ffd207cdb5',
        'max' => 'css/stylesheetFoo.max.css',
        'min' => 'css/stylesheetFoo.min.css',
    ),
    'stylesheetBar' => array(
        'md5' => '0aed497cc25bfc6ad59025ffd207cdb5',
        'max' => 'css/stylesheetBar.max.css',
        'min' => 'css/stylesheetBar.min.css',
    ),
);