<?php
# this file is auto-generated by bundler
return array (
  'stylesheetFoo' => 
  array (
    'md5' => 'acdd427c14f573e5ca70d7d23b20d8da',
    'max' => 'css/stylesheetFoo.max.css',
    'min' => 'css/stylesheetFoo.min.css',
  ),
  'stylesheetBar' => 
  array (
    'md5' => 'f7390884e6010f21df542b78f93f946b',
    'max' => 'css/stylesheetBar.max.css',
    'min' => 'css/stylesheetBar.min.css',
  ),
);